repository:
  # See https://github.com/probot/settings for all available settings.

  name: luna.github.io
  description: The developer documentation for the Enso compiler, runtime, and IDE.
  homepage: https://dev.enso.org
  topics: gh-pages, jekyll, static, developer-documentation, documentation-site

  private: false

  has_issues: true
  has_wiki: false
  has_projects: false
  has_downloads: false

  default_branch: sources

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

labels:
  - name: "Category: Light Theme"
    color: "#d1f0fd"
    description: The documentation's light theme
  - name: "Category: Dark Theme"
    color: "#d1f0fd"
    description: The documentation's dark theme
  - name: "Category: Functionality"
    color: "#d1f0fd"
    description: The documentation's functionality
  - name: "Category: External"
    color: "#d1f0fd"
    description: External issues

  - name: "Change: Breaking"
    color: "#ffdce5"
    description: A change that will break links to the site
  - name: "Change: Non-Breaking"
    color: "#ffdce5"
    description: A change that will not break links to the site

  - name: "Difficulty: Beginner"
    color: "#d1e9c4"
    description: Little prior knowledge required
  - name: "Difficulty: Core Contributor"
    color: "#d1e9c4"
    description: Should only be attempted by a core contributor
  - name: "Difficulty: Hard"
    color: "#d1e9c4"
    description: Significant prior knowledge required
  - name: "Difficulty: Intermediate"
    color: "#d1e9c4"
    description: Some prior knowledge required
  - name: "Difficulty: Unknown"
    color: "#d1e9c4"
    description: Unable to estimate difficulty

  - name: "Priority: High"
    color: "#fff1c1"
    description: Should be completed in the next sprint
  - name: "Priority: Highest"
    color: "#fff1c1"
    description: Should be completed ASAP
  - name: "Priority: Low"
    color: "#fff1c1"
    description: Should be completed in the next three months
  - name: "Priority: Lowest"
    color: "#fff1c1"
    description: Should be completed at some point
  - name: "Priority: Medium"
    color: "#fff1c1"
    description: Should be completed in the next few sprints

  - name: "Size: Small"
    color: "#ffdfd3"
    description: Requires a small time commitment
  - name: "Size: Medium"
    color: "#ffdfd3"
    description: Requires a medium time commitment
  - name: "Size: Large"
    color: "#ffdfd3"
    description: Requires a large time commitment
  - name: "Size: Unknown"
    color: "#ffdfd3"
    description: Requires an unknown time commitment

  - name: "Status: Cannot Reproduce"
    color: "#eeeeee"
    description: Can't reproduce the issue
  - name: "Status: Duplicate"
    color: "#eeeeee"
    description: A duplicate issue
  - name: "Status: Good First Issue"
    color: "#eeeeee"
    description: A good issue for new contributors
  - name: "Status: Help Wanted"
    color: "#eeeeee"
    description: Help wanted with the task
  - name: "Status: Info Needed"
    color: "#eeeeee"
    description: More information needed from submitter
  - name: "Status: Invalid"
    color: "#eeeeee"
    description: Not valid for some reason
  - name: "Status: Wontfix"
    color: "#eeeeee"
    description: Will not be fixed / not a bug

  - name: "Type: Bug"
    color: "#ede2fe"
    description: A bug in the docs site
  - name: "Type: Enhancement"
    color: "#ede2fe"
    description: An enhancement to the docs site
  - name: "Type: Discussion"
    color: "#ede2fe"
    description: A discussion about the docs site
