repository:
  # See https://github.com/probot/settings for all available settings.

  name: luna.github.io
  description: The developer documentation for the Enso compiler, runtime, and IDE.
  homepage: https://dev.enso.org
  topics: gh-pages, jekyll, static, developer-documentation, documentation-site

  private: false

  has_issues: true
  has_wiki: false
  has_projects: false
  has_downloads: false

  default_branch: sources

  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false

labels:
  - name: test
    color: 000000
    description: a test label
